{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "blekline-ingress.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "blekline-ingress.name" . }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "blekline-ingress.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: workspaceToken
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.workspaceToken.key }}
        property: {{ .Values.externalSecrets.remoteRefs.workspaceToken.property }}
    - secretKey: workspaceId
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.workspaceId.key }}
        property: {{ .Values.externalSecrets.remoteRefs.workspaceId.property }}
    - secretKey: sidecarAuth
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.sidecarAuth.key }}
        property: {{ .Values.externalSecrets.remoteRefs.sidecarAuth.property }}
---
{{- if .Values.trustVault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "blekline-ingress.fullname" . }}-vault
  labels:
    app.kubernetes.io/name: {{ include "blekline-ingress.name" . }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ default (printf "%s-vault" (include "blekline-ingress.fullname" .)) .Values.trustVault.masterKeySecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.trustVault.masterKeySecretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.vaultMasterKey.key }}
        property: {{ .Values.externalSecrets.remoteRefs.vaultMasterKey.property }}
{{- end }}
{{- end }}
